# Generated by Django 2.0.3 on 2018-03-25 02:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=9)),
                ('ano', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GastoMensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vencimento', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GastoSemanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diaVencimento', models.DecimalField(decimal_places=0, max_digits=2)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GastoUnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vencimento', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPagamento', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parcelas', models.IntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorMaoObra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('km', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automec.Carro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='peca',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automec.Servico'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automec.Servico'),
        ),
        migrations.AddField(
            model_name='custo',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automec.Servico'),
        ),
        migrations.AddField(
            model_name='carro',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='automec.Cliente'),
        ),
    ]
