# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('automec', '0003_auto_20160323_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 3, 24, 17, 47, 14, 912875, tzinfo=utc), verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 3, 24, 17, 47, 14, 912875, tzinfo=utc), verbose_name='data'),
        ),
    ]
